---
title: "Publications"
description-meta: "Publications and working papers by Wei Jin."
title-block-banner: false
toc: true
---

## Publications

- "Good Names Beget Favors: The Impact of Country Image on Trade Flows and Welfare", with Pao-Li Chang and Tomoki Fujii, *Management Science*, 2022, 68(10): 7555-7596.

- "The Trade and Welfare Effects of the Belt and Road Initiative", with Meng Gao, Chenxin Jin, Bin Sheng, and Linpu Xu, *Review of International Economics*, 2024, 32(2): 446-479.

- "Geopolitics along the Value Chains", with Renjing Chen, Chenxin Jin, Bin Sheng, and Guanxiang Wang, *China Economic Review*, 2025, Volume 90, p. 102341.

- "The Dynamic Trade and Welfare Effects of RCEP", with Chenxin Jin, Bin Sheng, Zhen Sun, and Bing Yan, *Journal of International Money and Finance*, 2025, Volume 154, p. 103329.

- "Comparative Advantage and Optimal Trade Policy with Strategic Interactions", with Mengmeng Dai, Wen-Tai Hsu, Yongjin Wang, and Siqiang Yang, *International Journal of Industrial Organization*, 2026, Volume 104, p. 103236.

- "The Depth of Preferential Trade Agreements", with Pao-Li Chang and Kefang Yao, *IMF Economic Review*, 2025, Accepted.

- "The Olympic Effect Revisited: 1950-2019", with Renjing Chen, Meng Gao, Wenzheng Gao, and Yuqian Sun, *World Development*, 2025, Conditionally Accepted.

## Working Papers

- "Yesterday Once More: The Impacts of Environmental Regulations on Multinational Corporations' Reinvestment Allocation in China", with Bing Yan, Shaoyu Guo, and Xiaojing Jiang, R&R at *Journal of Environmental Economics and Management*.

- "Guns and Gravity: Is There a Home-Market Effect in the Global Arms Trade?", with Meng Gao, Chenxin Jin, Chaodui Shao, Danni Su, Guanxiang Wang, and Mingyang Wei, R&R at *Review of International Economics*.

- "The GATT/WTO Welfare Effects: 1950-2015", with Pao-Li Chang and Kefang Yao, submitted.

- "Disentangling the Effects of GATT/WTO on Variable and Fixed Trade Costs: Trade Status, Trade Margins, and Export Sales Distribution", with Pao-Li Chang and Renjing Chen, submitted.

- "Diligence Redeems Stupidity: Managerial Effort Makes a Difference", with Renjing Chen, Yuting Chen, Meng Gao, and Jiantong Li.
